Dev alternative type
xbsoftware/querysql pull request #7
Opened 2024-05-20 13:47 UTC by epoddubskij

2024-05-20 14:44 UTC, mkozhukh requested changes

2024-05-20 14:44 UTC, mkozhukh commented on sql.go
> +			if pr, prOk := config.Predicates[data.Predicate]; prOk {
In think it has sense to return an error if Predicate was defined in configuration but can't be resolved ( as query will return wrong data in such case anyway )

2024-05-20 14:44 UTC, mkozhukh commented on sql.go
> +type CustomPredicate func(string, string, []interface{}) (string, []interface{}, error)
Its more complicated than necessary

`type CustomPredicate func(string, string) (string, error)`

predicates don't have any parameters, it's basically a name of an operator which need to be applied to a field before placing it in a sql operation

2024-05-20 16:01 UTC, epoddubskij commented
Corrected

2024-05-21 07:41 UTC, mkozhukh approved these changes

2024-05-21 07:41 UTC, merged